language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "w+V2zF2MhDhsAXDhi1c9pAGznGjo6coWffYM0FMQJGYhMtULbww1Wf3YUATEQ8TOl8iGh4ZdX7ZVHNFqbyEBNYl90cdOlpBp9n/4ngZfkyctoZ8CbAcA8IpWWxA2iHhR5m7KUJTFtzXcySDLiudPKRZDgAXe+bf/XfYll1uOhpToT9kYOhTew/BWeYy7QC98ILAYlGf0Am1ItstZU7bV1xAtEem4Q7OEZxKrWZng+IJUxx59D2Nx2Ui95kdeehvODTlfj1ko3tSXAqD6/S+6NM0pQ2Rc0rWzE+RbTukYare15hm35NCxsIca3HRXCiE8XTH6rKXyI6GmsDVZ4ts3yRJbRkJGb6xiQLW/VXHN9kwYrYh5yMdH9jSpLJ+Qnwe7qkj8uHw38obREaK5Fs1CNYQTsFf5AHGK00Gp8wfrWQfO8LuB/0p+JWzhoj9zq9uo8ORZEt5Rra5qPvi9mtwZvmcjeMQ58FicDVAP4UOTUUVdlvVd2wN+xyOiOVWQJbEpma2zkr/unYfHjgtiLCLuagEC1J8zm2s0Vt+ucGI1MhaPssQpRTuTTmV5V6Mvs6ioT5lzyfrJ1iHBolynhOJ2FVCRQ1O7ztDtoCoaVJ05japAyTzjk+wtm07MGyKkqyUEAcxfV5eio24+CDF2T5CIJm9CnJFSINOOrrzWrTO1vcQ="
    - secure: "AO07nhijl3WA/+8CZ9riF1WjDaZjUN/8j0R/HpPubmtTrB8XX85b+DvkMNOEqbC5vGFSArMWu8hv+G3W6OcsjsOIwcgNEFHCZzjR8UsfSHUgEHpt74PR+5TZvK/h76kxITh0GLRtIhKRt1TLRFMJJ1p8/ZANNV8+axTaAdxmkezuu4pOVG8ILlVIdhHlxl3mi+jdWxlHuJ98bLBLg7OVDuhyARct8+53Rist/oZ12Skc4ad9dRKSUbZfvVQCq6yJARukA5YMEHJ25JPMMbnKY0083noNys8zlPikQgX8VfTR8TKNVsrzOEeMu6KxV855vBTIgArdylD/diZe5DlLj9lKNCL8fsTigcy4Pk1HpK5e6yNeuCx7kuRDVYR3cUFmSqoHHDzuzh6gH3CEOoOpdy+64kxYbdxT1WFtgZwt95KjXjJPd/37EB0QRjF4c+R7n+OzFGoet5HZfazD3KMcnM7LfzlS0KHQVMK2lyeSOQUXiL9zmzqTpzLrTmVoB22qkSg5V8YgZeErnnmZnjOK7r6nIzz/RasF2AScC7Q7A9pg4S0AnD9Xt1wRvRTNNXbpOO7/hH16GgN1eH//fsuzx12rI1m7J18ySjICKSVdbTcOeZuUd9xX2tgo9yfsM2UkAGj3HDVLr+9y9iPhSvqWiJ77ywBanRP8oNvLsJImZ14="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./travis.sh
