dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "w+V2zF2MhDhsAXDhi1c9pAGznGjo6coWffYM0FMQJGYhMtULbww1Wf3YUATEQ8TOl8iGh4ZdX7ZVHNFqbyEBNYl90cdOlpBp9n/4ngZfkyctoZ8CbAcA8IpWWxA2iHhR5m7KUJTFtzXcySDLiudPKRZDgAXe+bf/XfYll1uOhpToT9kYOhTew/BWeYy7QC98ILAYlGf0Am1ItstZU7bV1xAtEem4Q7OEZxKrWZng+IJUxx59D2Nx2Ui95kdeehvODTlfj1ko3tSXAqD6/S+6NM0pQ2Rc0rWzE+RbTukYare15hm35NCxsIca3HRXCiE8XTH6rKXyI6GmsDVZ4ts3yRJbRkJGb6xiQLW/VXHN9kwYrYh5yMdH9jSpLJ+Qnwe7qkj8uHw38obREaK5Fs1CNYQTsFf5AHGK00Gp8wfrWQfO8LuB/0p+JWzhoj9zq9uo8ORZEt5Rra5qPvi9mtwZvmcjeMQ58FicDVAP4UOTUUVdlvVd2wN+xyOiOVWQJbEpma2zkr/unYfHjgtiLCLuagEC1J8zm2s0Vt+ucGI1MhaPssQpRTuTTmV5V6Mvs6ioT5lzyfrJ1iHBolynhOJ2FVCRQ1O7ztDtoCoaVJ05japAyTzjk+wtm07MGyKkqyUEAcxfV5eio24+CDF2T5CIJm9CnJFSINOOrrzWrTO1vcQ="
    - secure: "X0UyV52UIdhgYWgHPIQeJFuAsJoSw7hb6thccws9DC+AKbKRWQTA0TDw9zHhc2UbdEaplXx+Rz5hrL1f19hv5pc2WDLpkQRAqE1Xtdw6sLLzuVea3pCHvONgVkqJ1JXurkPcBqwtamWur+x7i3/LC7gA8k+cQogY8i4VP8z1kOE44ZZEbtA4lXPhApFnf5sOszR0XKQ7EF01vuNYFtZnUpmkzPH5l71ommAA5ugeo1YfODVusnEpocGby0bEFK0rycizxSajzf3+cZUvXtJtvxcLMYZR7eks2KvtPvTOO2e3vXLc7UHZpYoD7fNdv46ID5E5lTlFuKkHID7txVNnC2AfDOPWRT/mEJ9lMD2p031PsvnAkBMALJloyAABwRxPgdDAoA84OeawLtFfDTvQWCR3WmmxixnHmFlxnQMk5g5APjNGr14gP0HhwuUtOkGJWRjR+dkFuSM9TLmjJ49C9v4/X8o3eRhbBkHyxIbg7EjmLHBUsTz60311/XQgIDtbxbsvNvCGOI2lT66rtDuewv9rBjet0OkghX0T00fns3LnsxKwP1ERAgJo994sNDqIgDsKP9fDV0LwRGFWeE0JtpoBqYio5mLozB8yZe95ZE6ZlXwfjKKk+p84TbDelZPF6yABZkvxBOnVKp+Cmf6Xc56Ku0R0UamemUahI68jsMw="

  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
